### PR TITLE
Fix Widescreen for latest GitHub

### PR DESCRIPTION
**Pull request by brianlenz**
* Added a CSS style to fix the plugin to work with the latest GitHub DOM + CSS.

### CODE REVIEW

**Comment by sqren** [comment]
Thanks!

**Comment by sqren** [comment]
Released in v0.7.3

**Comment by brianlenz** [comment]
@sqren do you know how quickly Chrome typically updates the version in the web store? Still seeing `0.7.2`...

**Comment by sqren** [comment]
Oh, turns out it's a good idea to click "publish" after uploading the new version ;)
It should be available within the next few minutes.

**Comment by brianlenz** [comment]
Haha, cool thanks!

**Pull request merged**
